__author__ = 'holivares'

from django.db import models
from inei.auth.models import User


class Cuestionario(models.Model):
    usuario = models.CharField(max_length=20, db_index=True)
    proyecto = models.CharField(max_length=50, db_index=True)
    parte1_pregunta1 = models.TextField()
    parte1_pregunta2 = models.TextField()
    parte1_pregunta3 = models.TextField()
    parte1_pregunta4 = models.TextField()
    parte1_pregunta5 = models.TextField(null=True, blank=True)
    parte1_pregunta6 = models.TextField(null=True, blank=True)
    parte1_pregunta7 = models.TextField(null=True, blank=True)
    parte1_tiempo = models.IntegerField(null=True, blank=True)
    parte2_pregunta1 = models.CharField(max_length=2)
    parte2_pregunta2 = models.CharField(max_length=2)
    parte2_pregunta3 = models.CharField(max_length=2)
    parte2_pregunta4 = models.CharField(max_length=2)
    parte2_pregunta5 = models.CharField(max_length=2)
    parte2_pregunta6 = models.CharField(max_length=2)
    parte2_pregunta7 = models.CharField(max_length=2)
    parte2_pregunta8 = models.CharField(max_length=2)
    parte2_pregunta9 = models.CharField(max_length=2)
    parte2_pregunta10 = models.CharField(max_length=2)
    parte2_pregunta11 = models.CharField(max_length=2)
    parte2_pregunta12 = models.CharField(max_length=2)
    parte2_pregunta13 = models.CharField(max_length=2)
    parte2_pregunta14 = models.CharField(max_length=2)
    parte2_pregunta15 = models.CharField(max_length=2)
    parte2_pregunta16 = models.CharField(max_length=2)
    parte2_pregunta17 = models.CharField(max_length=2)
    parte2_pregunta18 = models.CharField(max_length=2)
    parte2_pregunta19 = models.CharField(max_length=2)
    parte2_pregunta20 = models.CharField(max_length=2)
    parte2_pregunta21 = models.CharField(max_length=2)
    parte2_pregunta22 = models.CharField(max_length=2)
    parte2_pregunta23 = models.CharField(max_length=2)
    parte2_pregunta24 = models.CharField(max_length=2)
    parte2_tiempo = models.IntegerField(null=True, blank=True)
    # parte3_pregunta1 = models.IntegerField()
    # parte3_pregunta2 = models.IntegerField()
    # parte3_pregunta3 = models.IntegerField()
    # parte3_pregunta4 = models.IntegerField()
    # parte3_pregunta5 = models.IntegerField()
    # parte3_pregunta6 = models.IntegerField()
    # parte3_pregunta7 = models.IntegerField()
    # parte3_pregunta8 = models.IntegerField()
    # parte3_pregunta9 = models.IntegerField()
    # parte3_pregunta10 = models.IntegerField()
    # parte3_pregunta11 = models.IntegerField()
    # parte3_pregunta12 = models.IntegerField()
    # parte3_pregunta13 = models.IntegerField()
    # parte3_pregunta14 = models.IntegerField()
    # parte3_pregunta15 = models.IntegerField()
    # parte3_pregunta16 = models.IntegerField()
    # parte3_pregunta17 = models.IntegerField()
    # parte3_pregunta18 = models.IntegerField()
    # parte3_pregunta19 = models.IntegerField()
    # parte3_pregunta20 = models.IntegerField()
    # parte3_tiempo = models.IntegerField(null=True, blank=True)
